"""PDF export of a schedule (SRS 3.9 — member can download assigned plan)."""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

ORANGE = colors.HexColor('#f97316')
DARK = colors.HexColor('#1f2937')
MUTED = colors.HexColor('#6b7280')
ROW_ALT = colors.HexColor('#f9fafb')


def build_schedule_pdf(schedule):
    """Render the schedule as a PDF and return it as bytes."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f'Workout Schedule — {schedule.title}',
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle('h1', parent=styles['Title'], fontSize=18, textColor=DARK,
                        alignment=0, spaceAfter=2)
    sub = ParagraphStyle('sub', parent=styles['Normal'], fontSize=10, textColor=MUTED,
                         spaceAfter=12)
    day_style = ParagraphStyle('day', parent=styles['Heading3'], fontSize=12,
                               textColor=ORANGE, spaceBefore=10, spaceAfter=4)
    normal = ParagraphStyle('normal', parent=styles['Normal'], fontSize=9.5, textColor=DARK)
    note_style = ParagraphStyle('note', parent=styles['Normal'], fontSize=9,
                                textColor=MUTED, spaceBefore=8)

    story = [
        Paragraph('EXFORCE GYM — Workout Schedule', h1),
        Paragraph(
            f'{schedule.title} &nbsp;&middot;&nbsp; {schedule.date_range_label} '
            f'&nbsp;&middot;&nbsp; Status: {schedule.status.label} '
            f'&nbsp;&middot;&nbsp; Version {schedule.version}',
            sub,
        ),
    ]

    info = Table(
        [
            ['Member', schedule.member.full_name, 'Trainer', schedule.trainer.full_name],
        ],
        colWidths=[22 * mm, 65 * mm, 22 * mm, 65 * mm],
    )
    info.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 9.5),
        ('TEXTCOLOR', (0, 0), (0, -1), MUTED),
        ('TEXTCOLOR', (2, 0), (2, -1), MUTED),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
        ('FONTNAME', (3, 0), (3, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, -1), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
    ]))
    story.append(info)

    # Group items by day, preserving sort order
    days = []
    for item in schedule.items:
        if not days or days[-1][0] != item.day_label:
            days.append((item.day_label, []))
        days[-1][1].append(item)

    for day_label, items in days:
        story.append(Paragraph(day_label, day_style))
        rows = [['Workout', 'Muscle Group', 'Sets', 'Reps', 'Rest', 'Notes']]
        for it in items:
            rows.append([
                Paragraph(it.workout.name, normal),
                it.workout.muscle_group.label,
                str(it.sets),
                it.reps,
                it.rest_label,
                Paragraph(it.notes or '—', normal),
            ])
        t = Table(rows, colWidths=[48 * mm, 30 * mm, 13 * mm, 18 * mm, 20 * mm, 45 * mm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), DARK),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ROW_ALT]),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#e5e7eb')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(t)

    if schedule.notes:
        story.append(Paragraph(f'<b>Trainer notes:</b> {schedule.notes}', note_style))

    story.append(Spacer(1, 10))
    story.append(Paragraph(
        f'Generated by Exforce GMS &middot; Plan version {schedule.version}',
        ParagraphStyle('footer', parent=styles['Normal'], fontSize=8, textColor=MUTED),
    ))

    doc.build(story)
    return buf.getvalue()