"""PDF receipt for a membership's verified payments (member self-service download)."""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

from app.utils.timezones import now_local

ORANGE = colors.HexColor('#f97316')
DARK = colors.HexColor('#1f2937')
MUTED = colors.HexColor('#6b7280')
ROW_ALT = colors.HexColor('#f9fafb')


def build_membership_receipt_pdf(membership, payments):
    """Render a payment receipt for the membership's verified payments.
    `payments` must already be filtered to PaymentStatus.VERIFIED and ordered
    oldest-first."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title=f'Payment Receipt - Membership #{membership.id}',
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle('h1', parent=styles['Title'], fontSize=18, textColor=DARK,
                        alignment=0, spaceAfter=2)
    sub = ParagraphStyle('sub', parent=styles['Normal'], fontSize=10, textColor=MUTED,
                         spaceAfter=12)
    note_style = ParagraphStyle('note', parent=styles['Normal'], fontSize=8.5,
                                textColor=MUTED, spaceBefore=10)

    receipt_no = f'GMS-RCPT-{membership.id}'
    member = membership.member

    story = [
        Paragraph('EXFORCE GYM - Payment Receipt', h1),
        Paragraph(
            f'Receipt No: {receipt_no} &nbsp;&middot;&nbsp; '
            f'Printed: {now_local().strftime("%d %b %Y, %H:%M")}',
            sub,
        ),
    ]

    info = Table(
        [
            ['Member', member.full_name, 'Member ID', str(member.id)],
            ['Email', member.email, 'Contact No', member.contact_no or '-'],
            ['Package', membership.package.name, 'Duration', membership.package.duration_label],
            [
                'Membership Period',
                f'{membership.start_date.strftime("%d %b %Y")} - {membership.end_date.strftime("%d %b %Y")}',
                'Status', membership.status_label,
            ],
        ],
        colWidths=[30 * mm, 62 * mm, 25 * mm, 55 * mm],
    )
    info.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 9.5),
        ('TEXTCOLOR', (0, 0), (0, -1), MUTED),
        ('TEXTCOLOR', (2, 0), (2, -1), MUTED),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
        ('FONTNAME', (3, 0), (3, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('LINEBELOW', (0, -1), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
    ]))
    story.append(info)
    story.append(Spacer(1, 14))

    rows = [['Date', 'Method', 'Reference No', 'Details', 'Amount (LKR)']]
    total = 0
    for p in payments:
        detail = '-'
        if p.installment:
            detail = f'Installment {p.installment.sequence_no} of {p.installment.plan.installment_count}'
        rows.append([
            p.payment_date.strftime('%d %b %Y'),
            p.method.label,
            p.reference_no or '-',
            detail,
            f'{p.amount:,.2f}',
        ])
        total += p.amount

    table = Table(rows, colWidths=[28 * mm, 28 * mm, 40 * mm, 42 * mm, 34 * mm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), DARK),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (4, 0), (4, -1), 'RIGHT'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#e5e7eb')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(table)

    total_table = Table(
        [['Total Paid', f'LKR {total:,.2f}']],
        colWidths=[138 * mm, 34 * mm],
    )
    total_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 10.5),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0, 0), (-1, -1), DARK),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(total_table)

    story.append(Paragraph(
        'This is a system-generated receipt for payments verified against this membership. '
        'For questions, please contact the gym reception.',
        note_style,
    ))
    story.append(Paragraph(
        'Generated by Exforce GMS',
        ParagraphStyle('footer', parent=styles['Normal'], fontSize=8, textColor=MUTED, spaceBefore=4),
    ))

    doc.build(story)
    return buf.getvalue()
